CREATE TABLE IF NOT EXISTS negative_keywords (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  level TINYINT UNSIGNED NOT NULL COMMENT '1=Campaign, 2=AdGroup', 

  campaign_id BIGINT UNSIGNED NOT NULL,

  adgroup_id BIGINT UNSIGNED NULL,

  broad JSON NOT NULL,

  phrase JSON NOT NULL,

  exact JSON NOT NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
