CREATE TABLE IF NOT EXISTS keywords (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  adgroup_id BIGINT UNSIGNED NOT NULL,

  status ENUM('ENABLED', 'PAUSED', 'REMOVED') NOT NULL DEFAULT 'PAUSED',

  broad JSON NOT NULL,

  phrase JSON NOT NULL,

  exact JSON NOT NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
